INSERT INTO department (id, name)
VALUES (1, 'Software Development'),
       (2, 'Product Management'),
       (3, 'Sales and Marketing'),
       (4, 'Research and Development'),
       (5, 'Human Resources');

INSERT INTO role (id, title, salary)
VALUES (1, 'Director of Engineering', 200000),
       (2, 'Front-end Developer', 100000),
       (3, 'Back-end Developer', 110000),
       (4, 'DevOps Engineer', 120000),
       (5, 'Director of Product Management', 180000),
       (6, 'Product Manager', 140000),
       (7, 'Business Analyst', 110000),
       (8, 'UX Designer', 110000),
       (9, 'Director of Sales', 200000),
       (10, 'Sales Representative', 80000),
       (11, 'Digital Marketing Specialist', 100000),
       (12, 'Account Executive', 150000),
       (13, 'Director of R&D', 200000),
       (14, 'Research Scientist', 120000),
       (15, 'Data Scientist', 120000),
       (16, 'Research and Development Engineer', 110000),
       (17, 'Director of HR', 180000),
       (18, 'Recruitment Specialist', 80000),
       (19, 'Employee Relations Specialist', 90000),
       (20, 'Compensation and Benefits Analyst', 100000);

INSERT INTO employee (id, first_name, last_name)
VALUES (1, 'John', 'Smith'),
       (2, 'Maria', 'Garcia'),
       (3, 'Mohammed', 'Abdul'),
       (4, 'Ling', 'Chen'),
       (5, 'Sven', 'Andersson'),
       (6, 'Léa', 'Dubois'),
       (7, 'David', 'Kim'),
       (8, 'Aisha', 'Al-Mansoori'),
       (9, 'Yuki', 'Nakamura'),
       (10, 'Elena', 'Ivanova'),
       (11, 'Carlos', 'Santos'),
       (12, 'Marta', 'Gomez'),
       (13, 'Chen', 'Li'),
       (14, 'Makoto', 'Suzuki'),
       (15, 'Olga', 'Petrov'),
       (16, 'Julia', 'Andersson'),
       (17, 'Wei', 'Wang'),
       (18, 'Anna', 'Kowalski'),
       (19, 'Rahul', 'Patel'),
       (20, 'Katja', 'Mäkinen'),
       (21, 'Mário', 'Silva'),
       (22, 'Sofia', 'Hernandez'),
       (23, 'Kenji', 'Tanaka'),
       (24, 'Hans', 'Jensen'),
       (25, 'Mia', 'Larsen'),
       (26, 'Sandeep', 'Sharma'),
       (27, 'Ewa', 'Nowak'),
       (28, 'Javier', 'Lopez'),
       (29, 'Inari', 'Korhonen'),
       (30, 'Juan', 'Gonzalez'),